version:  '3'
services:
  db:
    build: database
    ports:
      - "3366:3306"

  webapp:
    build: webapp
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db
